# src/main/resources/application-prod.yml
# Production configuration file

server:
  port: 8080
  address: 0.0.0.0

spring:
  profiles:
    active: prod
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  # Production logging configuration
  logging:
    level:
      org.springframework.security: INFO
      org.springframework.web: INFO
      com.diyawanna: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
      name: /root/logs/diyawanna-app.log
      max-size: 10MB
      max-history: 30

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds

# Management endpoints (for health checks)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized